name: Build rkp-ipid

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Linux kernel headers
        run: sudo apt-get install -y linux-headers-$(uname -r)

      - name: Install build dependencies
        run: sudo apt-get install -y build-essential

      - name: Build the kernel module
        run: make

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rkp-ipid-module
          path: |
            *.ko
